### ISSUE TITLE
TLV on RPi

### ISSUE THREAD

**Issue by VojislavM** [kostko/koruza-driver#1]
I tried to build this code on RPi2, but it showed me an error, actually it was warning that "make" interpreted es error. I have changed line 158:
```C
  printf("<Message tlvs(%lu)=[", message->length);
```
to:
```C
  printf("<Message tlvs(%u)=[", (unsigned int)message->length);
```
now it comiles and work on RPi2. Is the change ok?

I will try it on WiTi board next.

**Comment by kostko** [comment]
Ah yes, this is due to architecture differences. I've pushed your proposed fix.

**Comment by kostko** [comment]
BTW, for WiTi the easiest way is to make an OpenWrt package, similar to how it's done [here](https://github.com/wlanslovenija/firmware-packages-opkg/tree/master/util/nodewatcher-agent). I can also look into this.

**Comment by VojislavM** [comment]
Ok, that would be great. Thank you.

**Comment by kostko** [comment]
I have added an OpenWrt package feed containing the `koruza-driver` package here:
* https://github.com/IRNAS/koruza-openwrt-packages

I am building it right now to check whether it works correctly.
